//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventData) DeepCopyInto(out *CloudEventData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventData.
func (in *CloudEventData) DeepCopy() *CloudEventData {
	if in == nil {
		return nil
	}
	out := new(CloudEventData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefensiveAction) DeepCopyInto(out *DefensiveAction) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.ResourceRef != nil {
		in, out := &in.ResourceRef, &out.ResourceRef
		*out = new(ResourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefensiveAction.
func (in *DefensiveAction) DeepCopy() *DefensiveAction {
	if in == nil {
		return nil
	}
	out := new(DefensiveAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentDetection) DeepCopyInto(out *IncidentDetection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentDetection.
func (in *IncidentDetection) DeepCopy() *IncidentDetection {
	if in == nil {
		return nil
	}
	out := new(IncidentDetection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncidentDetection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentDetectionList) DeepCopyInto(out *IncidentDetectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IncidentDetection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentDetectionList.
func (in *IncidentDetectionList) DeepCopy() *IncidentDetectionList {
	if in == nil {
		return nil
	}
	out := new(IncidentDetectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncidentDetectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentDetectionSpec) DeepCopyInto(out *IncidentDetectionSpec) {
	*out = *in
	if in.CloudEvent != nil {
		in, out := &in.CloudEvent, &out.CloudEvent
		*out = new(CloudEventData)
		**out = **in
	}
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentDetectionSpec.
func (in *IncidentDetectionSpec) DeepCopy() *IncidentDetectionSpec {
	if in == nil {
		return nil
	}
	out := new(IncidentDetectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentDetectionStatus) DeepCopyInto(out *IncidentDetectionStatus) {
	*out = *in
	if in.ActionsExecuted != nil {
		in, out := &in.ActionsExecuted, &out.ActionsExecuted
		*out = make([]DefensiveAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.OSINTData != nil {
		in, out := &in.OSINTData, &out.OSINTData
		*out = make(map[string]interface{}, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentDetectionStatus.
func (in *IncidentDetectionStatus) DeepCopy() *IncidentDetectionStatus {
	if in == nil {
		return nil
	}
	out := new(IncidentDetectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}
