{{- if .Values.honeypot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: honeypot-web-content
  namespace: {{ include "the-mirror.namespace" . }}
  labels:
    {{- include "the-mirror.labels" . | nindent 4 }}
    app: simple-honeypot
data:
  index.html: |
{{ .Files.Get "config/honeypot/index.html" | nindent 4 }}
  robots.txt: |
{{ .Files.Get "config/honeypot/robots.txt" | nindent 4 }}
  admin.html: |
{{ .Files.Get "config/honeypot/admin.html" | nindent 4 }}
  .credentials: |
{{ .Files.Get "config/honeypot/.credentials" | nindent 4 }}
{{- end }}
