{{- if and .Values.agent.enabled .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror-agent-audit-pvc
  namespace: {{ include "the-mirror.namespace" . }}
  labels:
    {{- include "the-mirror.labels" . | nindent 4 }}
    app: mirror-agent
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
